services:
  mysql:
    image: mysql:8.0
    container_name: parking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parking
      MYSQL_USER: parking
      MYSQL_PASSWORD: parking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - parking-network

  simulator:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: parking-simulator
    ports:
      - "8080:3000"
    networks:
      - parking-network
    environment:
      - WEBHOOK_URL=http://host.docker.internal:3003/webhook
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql_data:

networks:
  parking-network:
    driver: bridge
