server:
  port: ${SERVER_PORT:3003}

spring:
  application:
    name: parking
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:parking}?serverTimezone=UTC&useTimezone=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
  jackson:
    property-naming-strategy: SNAKE_CASE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

simulator:
  base-url: ${SIMULATOR_BASE_URL:http://localhost:8080}

pricing:
  occupancy-rate:
    threshold-low: 0.25
    threshold-medium: 0.5
    threshold-high: 0.75
  price-factor:
    low: 0.9
    normal: 1.0
    medium: 1.1
    high: 1.25
  decimal-scale: 2

logging:
  level:
    com.estapar.parking: INFO
    com.estapar.parking.config.WebhookLoggingFilter: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
